import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('screen');
const h = height;
const w = width;

const Styles = StyleSheet.create({
  maincontainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    // backgroundColor: 'blue',
    height: '8%',
    width: '100%',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  imgView: {
    height: '7%',
    width: '100%',
    // backgroundColor: 'pink',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  profileView: {
    height: '25%',
    width: '100%',
    // backgroundColor: 'gray',
    flexDirection: 'row',
  },
  profileImg: {
    // backgroundColor: 'red',
    height: '100%',
    width: '50%',
    borderBottomRightRadius: 50,
    overflow: 'hidden',
  },
  editPhoto: {
    backgroundColor: '#ffff',
    height: '15%',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 3,
  },
  profileInfo: {
    height: '100%',
    width: '50%',
    // backgroundColor: 'yellow',
    justifyContent: 'space-evenly',
    paddingLeft: 10,
  },
  editProfile: {
    backgroundColor: '#06155a',
    height: '15%',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  profileView2: {
    height: '25%',
    width: '100%',
    // backgroundColor: 'gray',
    flexDirection: 'row',
  },
  profileInfo2: {
    height: '100%',
    width: '50%',
    // backgroundColor: 'yellow',
    justifyContent: 'space-evenly',
    paddingLeft: 10,
  },
  profileInfo3: {
    height: '100%',
    width: '50%',
    // backgroundColor: 'red',
    justifyContent: 'space-evenly',
    paddingLeft: 10,
    alignItems: 'flex-end',
    marginRight: 10,
  },
  View: {
    // backgroundColor: 'pink',
    height: '9%',
    width: '100%',
    flexDirection: 'row',
  },
  following: {
    // backgroundColor: 'red',
    height: '100%',
    width: '33%',
    borderWidth:0.2,
    alignItems:'center',
    justifyContent:'center',
  },
  followers: {
    // backgroundColor: 'blue',
    height: '100%',
    width: '33%',
    borderWidth:0.2,
    alignItems:'center',
    justifyContent:'center',
  },
  posts: {
    // backgroundColor: 'gray',
    height: '100%',
    width: '33%',
    borderWidth:0.2,
    alignItems:'center',
    justifyContent:'center',
  },
  View2: {
    backgroundColor: '#06155a',
    height: '9%',
    width: '100%',
    flexDirection: 'row',
    marginTop:5,
  },
  paidMsg:{
    height: '100%',
    width: '33%',
    borderWidth:0.2,
    alignItems:'center',
    justifyContent:'center',
  },
  directMsg:{
    height: '100%',
    width: '33%',
    borderWidth:0.2,
    alignItems:'center',
    justifyContent:'center',
  },
  cashRew:{
    height: '100%',
    width: '33%',
    borderWidth:0.2,
    alignItems:'center',
    justifyContent:'center',
  },
  View3: {
    // backgroundColor: '#06155a',
    height: '9%',
    width: '100%',
    flexDirection: 'row',
    marginTop:5,
  },
  posts:{
    height: '100%',
    width: '50%',
    borderWidth:0.5,
    alignItems:'center',
    justifyContent:'center',
  },
  tags:{
    height: '100%',
    width: '50%',
    borderWidth:0.5,
    alignItems:'center',
    justifyContent:'center',
  },
});
export default Styles;
